# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FL98fBuGTHngGoM4-Pt4TVqfU66qyBPc
"""

from IPython.display import Audio
from scipy.io import wavfile
import numpy as np

file_name = 'audio.wav'

Audio(file_name)

data=wavfile.read(file_name)
framerate=data[0]
sounddata=data[1]
time=np.arange(0,len(sounddata))/framerate
print(framerate)
print('Total time:',len(sounddata)/framerate)

!pip install -q transformers librosa --quiet

import soundfile as sf
import librosa
import torch
from transformers import Wav2Vec2ForCTC, Wav2Vec2Tokenizer

from transformers import Wav2Vec2ForCTC, Wav2Vec2Tokenizer

tokenizer = Wav2Vec2Tokenizer.from_pretrained("facebook/wav2vec2-base-960h")
model = Wav2Vec2ForCTC.from_pretrained("facebook/wav2vec2-base-960h")

input_audio,_ = librosa.load(file_name,sr=16000)

input_values = tokenizer(input_audio,return_tensors="pt",padding="longest").input_values
with torch.no_grad():
     logits = model(input_values).logits
     predicted_ids = torch.argmax(logits,dim=-1)
     text = tokenizer.batch_decode(predicted_ids)[0]

text
